services:
  mongodb:
    build:
      context: ./docker/mongo
      dockerfile: Dockerfile
    container_name: mongo-db
    ports:
      - '27017:27017'
    env_file: .env
    environment:
      - 'MONGO_INITDB_DATABASE=kafka-book'
      - 'MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}'
    restart: on-failure
    volumes:
      - ./docker/mongo/scripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mongo", "--eval", "rs.status()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - bubble

networks:
  bubble:
    driver: bridge
