services:
  mongodb:
    image: 'mongo:nanoserver-ltsc2022'
    env_file: .env
    environment:
      - 'MONGO_INITDB_DATABASE=kafka-book'
      - 'MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}'
    ports:
      - '27017:27017'
    hostname: mongodb
    container_name: mongo-db
    restart: on-failure
    volumes:
      - ./src/main/resources/scripts/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js:ro
    command: mongod
    healthcheck:
      test: ["CMD", "mongo", "--eval", "rs.status()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - bubble

networks:
  bubble:
    name: bubble
    driver: bridge
